### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by AbhijeetSG** [toebes/ciphers#105]
2018 North Carolina Regional and State Tests Links are throwing 404 Not Found Error.
Sample Reference Link: 
https://toebes.com/codebusters/Samples/Code%20Busters%202018%20Test%201.pdf

**Comment by RanTheLab** [comment]
Duplicate #104

**Comment by toebes** [comment]
The directory had gotten renamed.  it is back in place.  Thanks for reporting it.
