### ISSUE TITLE
Document file format for QuoteAnalyze, or provide plain-text upload

### ISSUE THREAD

**Issue by jlwether** [toebes/ciphers#118]
CodeBusters question: The QuoteAnalyze page looks like it might be useful, but when I try to use it, it asks for a .json file.  How should the .json file be formatted?  I guess what I'm asking is what type of object is being represented by the .json file.  
Alternatively, some way to upload a plain text file into this tool would be  helpful, as long as the input format is documented.

**Comment by toebes** [comment]
Good point... I'll try to add some documentation to the page, but in the meantime, here's a simple format to use: 
  Start with a single left square bracket and end with a right square bracket.  Put {} around each entry with "text": "<the text you want to encode>, "author": "<name of author>

Remember to put a comma between each set but not after the last one.

```
[
 {"text": "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "author": "Albert Einstein"},
 {"text": "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", "author": "Isaac Asimov"}
]
```

**Comment by jlwether** [comment]
Thanks.  Interesting tool.  It looks like it is heading toward a quote
management system with notes, when used, etc.  That would be pretty cool.
