### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by ghost** [toebes/ciphers#119]
Hello

 
How to save the paper into word?
Please provide an option to print out.

Thanks

**Comment by toebes** [comment]
I am going to need a bit more information about your situation.  I've tested with Firefox, Chrome, Edge and Safari on Windows and Mac.  From there I've been able to print using the standard browser print functions (^P on Windows) (⌘P on Mac OS X).  In addition to printing on the printer, I can also print to PDF and open it up.  What browser/OS are you using?

**Comment by karthikk7193** [comment]
Thanks for the information. Can you please let me know how to save it to PDF or Word Document

**Comment by RanTheLab** [comment]
Using any of the standard browsers, you should be able to print to PDF instead of a physical printer.  Saving to a Word Document is not supported.

**Comment by karthikk7193** [comment]
Thanks.

Sincerely,
Karthik Kumar

*If opportunity doesn't knock, build a door ~ Milton Berle*

**Comment by RanTheLab** [comment]
Closing.
