### ISSUE TITLE
Hill Cipher Printing Oddly

### ISSUE THREAD

**Issue by InvisibleIncubus** [toebes/ciphers#122]
This is what my Hill Ciphers look like in the test packet. The decrypt ones look odd as well. Am I doing something wrong?
![hill issue](https://user-images.githubusercontent.com/46539793/51645362-1e140d80-1f31-11e9-81e2-6059e273e1e2.png)

**Comment by toebes** [comment]
That's definitely a bug.  I can reproduce it here and will try to get a fix out in the next day or so.

**Comment by InvisibleIncubus** [comment]
FYI, it's still happening. 
![hill issue2](https://user-images.githubusercontent.com/46539793/52527541-57fe4700-2c87-11e9-9fb3-e14ba44302c3.png)

**Comment by toebes** [comment]
It has been fixed.  Thanks for the nudge!
