### ISSUE TITLE
test packet, etc. won't load

### ISSUE THREAD

**Issue by InvisibleIncubus** [toebes/ciphers#125]
I made a practice test today, and when I click on "test packet" or try to print (to .pdf) the test packet, only the instruction pages and the first three questions appear, as well as this huge menu at the top of the page. Tests I made previously still work fine, and I don't get the huge menu with them. 

![menu](https://user-images.githubusercontent.com/46539793/54779118-04fba600-4bdc-11e9-9570-3f5ad1fdfa40.png)

**Comment by toebes** [comment]
If you could please email a copy of the test.json file to john@toebes.com I will debug the problem.  We saw one other case of this and couldn't reproduce it, it is related to the code that generates the test question and can fix it once we know what causes it.  Just go to edit the test, export the test to get the .json file.

Thank you very much!

**Comment by toebes** [comment]
Unfortunately Github doesn't let you attach to a response.  Please send the file directly to me at john@toebes.com (replying doesn't actually go to the right place)

**Comment by toebes** [comment]
Ok I see the problem. Question 3 on the test was a Compute the Inverse Matrix for a Hill 3x3 Cipher, but that is not supported (nor legal on a test).  I'm working on a fix to not crash the code and should have it pushed out soon.

**Comment by toebes** [comment]
It has been fixed to generate an appropriate message instead of crashing.

**Comment by InvisibleIncubus** [comment]
Thank you! I know the 3x3 decrypt won't be on the test, but my son loves doing more challenging matrices, so that was for his entertainment. Thanks for all you do for this event.
