### ISSUE TITLE
viewing test packet

### ISSUE THREAD

**Issue by azhang941** [toebes/ciphers#126]
second time this happened, I can't view the test packet, I only see the menu and the timed question

**Comment by azhang941** [comment]
it appears as if the morbit cipher is the cause of the problem (i can view all ciphers up to morbit)

**Comment by toebes** [comment]
Hi @azhang941 ,
  We have been furiously fixing bugs in the Morbit solver, if you could please email the test which is causing the problem to john@toebes.com we will find and squash that bug!  Thank you very much

**Comment by toebes** [comment]
Ok we are pretty sure we found the bug and fixed it.  Let us know if you have any other problems.
