### ISSUE TITLE
false alarm

### ISSUE THREAD

**Issue by will0416** [toebes/ciphers#131]
issue fixed

**Comment by RanTheLab** [comment]
I took a quick look and noticed Affine was not in the drop down list and was going to add it.  What was your fix?

**Comment by will0416** [comment]
I just selected that the test was a div C invitational/regional level test. The affine cipher was missing from the original drop down list, however.

**Comment by RanTheLab** [comment]
With commit fab4b74, affine is now in the dropdown list even if the test type is not set.
