### ISSUE TITLE
tap code division A line break error

### ISSUE THREAD

**Issue by baileyc619** [toebes/ciphers#132]
Some of the dot are splitting across rows, making it difficult to determine what goes together. for example, T is 4 dots followed by 4 dots. I have had 3 dots show up on one line and the next line have the 1 dot by itself followed by the other 4 dots. 

Love this time saving program! :)

**Comment by RanTheLab** [comment]
Please provide you plaintext which exhibits the behavior you are seeing with the line breaks and I will work on fixing it.
Glad you are finding the site useful!

**Comment by baileyc619** [comment]
This is the text I used: 

There are twenty four bags of pretzels in a box. How many pretzels are there if there are two hundred thirty four pretzels in each bag?

It split two letters "mid-dot."

**Comment by RanTheLab** [comment]
Thanks! I see the behavior and will investigate.
