### ISSUE TITLE
Morbit and Pollux tools should trim leading x characters from the Morse code

### ISSUE THREAD

**Issue by jlwether** [toebes/ciphers#134]
I love the new Morbit and Pollux tools for Codebusters.  It is especially nice that they automatically remove unnecessary trailing x (divider) characters from the Morse code, as these could easily be introduced from a final period or other punctuation.  Unfortunately, it doesn't currently remove leading x characters that are introduced into the Morse code.  The tool user can fix this this manually by removing all leading spaces and punctuation, but this isn't always obvious, especially in the case of leading quotation marks.  

On a related note, the automated solver gets totally confused if the first Morse character is x.

**Comment by toebes** [comment]
Good catch!  Agreed that the solvers never expect to see the leading X.
