### ISSUE TITLE
Decryption Key for Hill cipher

### ISSUE THREAD

**Issue by FarzanS1** [toebes/ciphers#135]
On rule vii. It states that decryption of Hill Cipher has the decryption key already provided to you. Toebes doesn't do this whenever you make a decryption problem

**Comment by toebes** [comment]
There was a rule clarification posted yesterday at https://www.soinc.org/events/rules-clarifications

> 11/19/19 (Division C) 3.e.vii. should read, edits in bold: "the Hill Cipher - encrypting plaintext or decrypting ciphertext given a 2x2 encryption matrix." (encryption replaces the incorrect term decryption)

As such the tool is correct and doesn't need an update.
