### ISSUE TITLE
division -B

### ISSUE THREAD

**Issue by nature812** [toebes/ciphers#139]
Division B - Invitationals rules say there can be two encode problems. TOebes does not allow to create encode questions
Thanks
V

**Comment by RanTheLab** [comment]
Please provide additional information such as the rule number, cipher type, etc.  you are referring to.

**Comment by nature812** [comment]
Code Busters B 2020 SOCAL Event

3.h
No more than 2 cipher questions will be encryption on the exam

**Comment by RanTheLab** [comment]
Thanks for the additional information.  It would be the responsibility of the event leader (or the author of the test) to be sure the event test adheres to rule 3.h.  Some possible cipher types to use to create **no more than two** encryption questions are 3.e.i, 3.e.ii, 3.e.iv, 3.e.v.
There is some guidance for writing a test here: https://toebes.com/codebusters/TestGuidance.html
A good idea might be to review some of the tests from previous years to get an idea of the question style and flavor.
