### ISSUE TITLE
Student name and school name rows are missing

### ISSUE THREAD

**Issue by nature812** [toebes/ciphers#140]
Hello

After creating paper, when I try to print or save, Student names and School names rows are missing

Thanks
V

**Comment by RanTheLab** [comment]
![TestEditor](https://user-images.githubusercontent.com/7691169/71209893-ac485f00-227a-11ea-8b65-0dc9e9ca392e.png)

On the test generator screen, please check that you have not enabled (as shown in the image) the "Custom Header" which replaces the student and school names section with custom HTML.  If you have not provided any custom HTML, nothing will be printed causing the behavior you've described.

**Comment by nature812** [comment]
Thanks a lot. Appreciate your quick email.
V

**Comment by RanTheLab** [comment]
You're welcome!
