### ISSUE TITLE
Morbit and Pollux

### ISSUE THREAD

**Issue by nature812** [toebes/ciphers#142]
Hello

There was explanation for Morse and Pollux ciphers as they are new. Now I do not see it, Can you help me out with where I can find explanation in the site
Thanks
V

**Comment by RanTheLab** [comment]
There is some explanation here: https://toebes.com/codebusters/TestGuidance.html

- https://www.cryptogram.org/downloads/aca.info/ciphers/Morbit.pdf

- https://www.cryptogram.org/downloads/aca.info/ciphers/Pollux.pdf
and
- https://www.dcode.fr/morbit-cipher

- https://www.dcode.fr/pollux-cipher

**Comment by toebes** [comment]
Also in additional to the automatic solvers when you generate a question, we have an explanation at:
https://toebes.com/codebusters/Samples/Solving_Morbit.htm
https://toebes.com/codebusters/Samples/Solving_Pollux.htm
