### ISSUE TITLE
Morbit Generator

### ISSUE THREAD

**Issue by Rilakamii** [toebes/ciphers#144]
I was trying to make a test for pollux/morbit practice. I generated 5 pollux ciphers with no issue, but then I went to make a morbit cipher, tried to use the question text autogenerator, but when I hit the suggested question text button, it didn't do anything so I saved the problem and refreshed the page. Now every time I try to open the problem it will give me this screen. I am now unable to open the edit test menu, because it will only open to this screen with the morbit suggested text message on the bottom. I also tried to duplicate the test and then work on that one to see if that would fix it but it has the same problem. Is this a glitch? How do I fix it? 
![image](https://user-images.githubusercontent.com/60299078/73125750-57ce8880-3f78-11ea-8939-f8e95a5e73aa.png)

**Comment by RanTheLab** [comment]
"Show suggested test question" creates a popup window with buttons to copy to clipboard, replace question text and close the window.  If you do not see this popup window, please make sure pop-ups are not blocked for this page.
The behavior you are describing usually means an error has occurred.  The errors are often displayed in the browser console.  This page https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors can help you find the browser console for your specific operating system and browser.  Please provide us with any information from the browser console when this error occurs.  The details of your question (plain text, hint digits, etc.) may also help.

**Comment by RanTheLab** [comment]
I have recreated the error.  You can disregard my previous comment.  Will work on a fix.
