### ISSUE TITLE
Affine test guidance typos

### ISSUE THREAD

**Issue by jlwether** [toebes/ciphers#145]
The sample question text for Affine Cipher decrypt should say "Decode the following..." (not "Encode"); likewise, the sample question text for Affine Cipher encrypt should say "Encode the common phrase..." (not "Decode").  Actually, I would prefer "Decrypt" and "Encrypt" to "Decode" and "Encode", but that is just my preference; it is much more critical to get the direction of Plain->Cipher or Cipher->Plain correct.

**Comment by RanTheLab** [comment]
Will be fixed in the next site update shortly...
