### ISSUE TITLE
Create interactive Test tool for Pollux/Morbit Cipher

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#177]

**Comment by RanTheLab** [comment]
@toebes -- thoughts?

**Note**:  Mobit and Pollux encoders are in 2 different  source files.

I will tackle morbit first.  Here is a simple mockup:

![image](https://user-images.githubusercontent.com/7691169/93730708-cf9c9380-fb97-11ea-9565-321d9c6d61e9.png)

The **Decodes** (for lack of better term) will use the **replacements** field.  The Answer will use the **answer** field.  Each of the Decodes and Answer lines will have two input fields below each number.  (The Decode would **not** be pre-filled in as in the mockup.)

There will be markers on each field (much like baconian).  Perhaps the Decodes fields will only take ".", "-", "x" as inputs and print out ●–×.  The students could use the **Notes** to build the table (may be tedious).  An alternative would be to use the **replacements** field for the decode table, but I like the first suggested use of replacements.

This model works for 'decode' and 'cryptanalysis' of morbit.

I suspect the scoring for this will be much like the baconian, too!

**Comment by toebes** [comment]
I definitely like.   We probably want to let them put in ? - . x as inputs since they might have something that could be either - or .  
I'm wondering if we want to also give them an extra table before the notes of the form:

| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
|-|-|-|-|-|-|-|-|-|
| ●● | ●– | ●× | –● | ‗‗‗  | ‗‗‗  | ‗‗‗ | ‗‗‗ | ‗‗‗  |

With slightly wider input fields and allowing them to type anything into it (with . going to ●, - goes to – and x goes to ×.

For scoring it is fairly simple.  Take all the answer fields and concatenate them throwing out / and spaces.
