### ISSUE TITLE
Track potential cheating

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#193]
Each question tracks a local variable for the confidence.  It is calculated as follows: 
1.  Each question stores a natural boundary (1 for most, 2 for 2x2 hill and 3 for 3x3 hill) and a nominal speed value (1 second for a atbash, 2 seconds for caesar, 5 seconds for aristocrat, 3 seconds for vigenere) [values to be tuned]
1. When entering a letter on a `.awc` field, it gets the ID and the question number.  If the question number is the same as the last one done and the ID is one more than the previous one (discounting things that aren't on boundaries) then we compute a confidence factor which is the nominal speed value - the time between letters with a log factor as the time gets shorter.
1. Entering a letter into a `.awr` field resets the previous letter so the step above doesn't add a value.  Also, typing into the text box does a similar reset.
The confidence value is added to the local value for the question.
1. All confidence values for all questions are added and put into the overall confidence shared value for the user in the answertemplate

There are several tuning knobs, but the general algorithm won't impose a burden on the test running.

Whenever the confidence value hits certain thresholds (TBD), it increments a to-be-added field value in the answertemplate.assigned entry (ITestUser) for that user.  This allows all other test takers sharing that test to see updated information about potential cheating by their partner (exact display TBD)

**Comment by jlwether** [comment]
For longer problems such as patristocrats, I would encourage students to copy the problem to paper and solve it on paper.  I admit I don't fully understand the proposal, but it sounds like this would flag anyone who partially solves a problem on paper and then quickly enters what they have.  That doesn't make it bad, necessarily, but I wonder about flagging things for other students to see.
