### ISSUE TITLE
Need to support tie breaking between two different tests.

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#196]

**Comment by RanTheLab** [comment]
need to compare and rank all tests in a tournament....break the ties.

**Comment by RanTheLab** [comment]
Look at https://www.datatables.net/

**Comment by toebes** [comment]
The order of tiebreaker questions is based on the score of the question and the order it is on the test.  Highest scoring questions are first and when two questions have the same score value, the question which appears later on the test (i.e. has the higher question number) is higher priority for breaking ties.

Tiebreaking is done in two stages:

### Stage1: 
To determine how to break the tie, you need to look at the correctly answered questions in the order from the tie breaking table. If both teams answered the same (i.e. they answered the question with zero mistakes) then you go on to the next question. If one team had no mistakes and the other team had one mistake, then the team with no mistakes is ahead. For example, if one team answered the highest value question and another team didn't, the first team will be ahead.

### Stage 2: 
If there is still a tie (typically when you have teams which answered either zero, one or two questions) then you will need to look at the tie breaker questions again and count the number of correctly answered letters. The team with the most correctly matched letters is to be ahead.
