### ISSUE TITLE
The student could not access the test

### ISSUE THREAD

**Issue by rpochana** [toebes/ciphers#217]
I published a test for several students, but one particular student has issue. She couldn't see it as a scheduled test for her. I gave the test link directly, but she couldn't access even with that link. The browser is chrome. We tried in Incognito mode too. We tried two logins - one personal gmail and another is a school email account.
These are the test instances for this particular test. 
https://toebes.com/codebusters/TestTimed.html?testID=d474be6c-ec6c-48d9-ad62-e47599c7e52d
https://toebes.com/codebusters/TestTimed.html?testID=24b68c2a-0bfa-4b6f-b2a1-c0922cb6b715

The test id of the test is testID=56622d84-7cb1-4a19-8e63-62dc9d22c518

**Comment by toebes** [comment]
We've made quite a few fixes in this area.  Does the problem still exist?

**Comment by toebes** [comment]
If you encounter this problem again, please feel free to reopen the issue
