### ISSUE TITLE
Issue with multiple teams accessing a test

### ISSUE THREAD

**Issue by Gates-Codebusters** [toebes/ciphers#218]
I created a test and scheduled it at the same time for 2 teams. One team all the members were able to open the test. For the other team, both members got the following error message:

Convergence API could not open data model: Error: Must have read privileges to open model. 
Names of participants:
<omitted for privacy>

It may be that I just set the permissions incorrectly, so this may not be an issue. When I created a duplicate version of the test, and published 2 separate tests as interactive tests, one for each team, they were able to access successfully.

**Comment by toebes** [comment]
Hi, 
  Could you give us the ID of the test (it will be in the URL at the top) so that we can track down what is going on?

Thank you for your patience in helping get this resolved!

**Comment by Gates-Codebusters** [comment]
https://toebes.com/codebusters/TestGenerator.html?test=3
This is the test I originally published, and had the error message when the
second team tried to open it. I then duplicated that test, and saved it as
a V1 and V2, and scheduled each team separately, one for each version. This
seemed to work, but in hindsight it wasn't a perfect test, as I changed two
variables at once. I used the two versions, but also scheduled the start
times to be offset, so can;t identify with certainty which change worked.
Please let me know if you have additional questions.

Thanks,
Jeff Gates

**Comment by toebes** [comment]
Actually you will need to go to the schedule test page in order to get the id of the test on the server (it will be a long string of numbers like : 4c9220b9-0576-4219-8452-6a9746879129).  That way we can check the permissions on the server to figure out what is going on.

**Comment by Gates-Codebusters** [comment]
John -

I just discovered another issue. The team was able to complete the V1
version of the test I scheduled for them, but the scoring seems incorrect.
When I click on Analyze, they have the correct solution. But when I click
on Details, it shows them with 8 incorrect letters, and 0 points. I am
assuming that you can access these URLs directly, but if not, I can send
you screenshots.

https://toebes.com/codebusters/TestResults.html?testID=14c6ac88-1625-480b-adc9-b49e1a0a731b

Thanks,
Jeff Gates

**Comment by Gates-Codebusters** [comment]
OK, sorry about that. I think this should be it.

https://toebes.com/codebusters/TestResults.html?testID=f803868f-9d19-4d8d-af97-ca21b23a9fc2

**Comment by RanTheLab** [comment]
Jeff, we think the permissions problem is occurring on the server.  We have [opened a bug](https://github.com/convergencelabs/convergence-project/issues/193) against the server.  

We are looking at the scoring issue.  Please open another bug here to track that problem and you will be notified of when it gets fixed.
Thanks!

**Comment by Gates-Codebusters** [comment]
Thanks for the update.

On the scoring bug, happy to go report it in the forum, but have a quick
question first. The link I posted with the tes results showed the emails of
the students that took the test. Can I report the issue without the link,
and have a follow up via email as necessary to provide the details to allow
you to track the specific test? I don't want all of the identifying info to
be available for everyone to see.

Thanks,
Jeff

**Comment by RanTheLab** [comment]
I think we have all we need for scoring bug.  If not I will let you know.

**Comment by toebes** [comment]
Even with the IDs, nobody other than you and the admins can see any of the identifying information of the students.  We have made sure that the security of the system is such that only the coaches/students can see who is on the test.  All of our server admins which have access to the information on the backend have gone through background checks and safe child training.  Basically you only can see information which you already knew and nothing else.

**Comment by toebes** [comment]
We've made quite a few fixes in this area over the past couple of months. Can you please let us know if the problem still exists?

**Comment by toebes** [comment]
If you encounter this problem again, please feel free to re-open this issue

**Comment by Gates-Codebusters** [comment]
That problem seems to be fixed. But as an FYI, I think you may be having an
issue with permissions on published tests at the moment. I can normally
only see the tests I have created, but at the moment, I can see hundreds of
tests (potentially all of them). One of them was labeled the NC State test.
It did not have the year, but if it is for the upcoming States, I wanted to
make sure you were aware that it was accessible at the moment so you could
shut that down.

Thanks,
Jeff Gates

**Comment by toebes** [comment]
Thank you for pointing it out.  We just pushed an update.  Fortunately the upcoming states tests are not visible.

**Comment by toebes** [comment]
Ok we fixed it.  Thank you very much!
