### ISSUE TITLE
Potential error in scoring

### ISSUE THREAD

**Issue by Gates-Codebusters** [toebes/ciphers#219]
I had some students take a practice test using the interactive test feature, but the scoring seems incorrect. When I click on Analyze, they have the correct solution. But when I click on Details, it shows them with 8 incorrect letters, and 0 points for that question.

**Comment by RanTheLab** [comment]
What was the question text on the one that did not score?

**Comment by Gates-Codebusters** [comment]
Here is a screen shot of the question.

[image: image.png]
And here is the scoring that I see:
[image: image.png]

Please let me know if you need anything else

Thanks,
Jeff

**Comment by RanTheLab** [comment]
I am not seeing the images, but figure it is the 'think like a proton always positive'.  Is the by chance the question that you changed?  If so, what did you change?

**Comment by Gates-Codebusters** [comment]
Sorry about that. Will try again; please let me know if you can see the
question below. The plain text should be "Our team will do well in
codebusters on Saturday"

They had this correct, but it indicates that 8 letters are incorrect, and
deducts all the points from their total.



Timed Question [100 points] DUP

Solve this cipher that predicts the future. Hint: m=n
 When you have solved it, click the *Checked Timed Question* button so that
the time can be recorded and the solution checked.
L F I G V Z N D R O O W L D V O O R M X L W V Y F H G V I H L M H Z G F I W
Z B
Our team will do well in codebusters on Saturday

QuestionValueCipher typeIncorrect lettersDeductionScore
Timed 100 atbash 8 100 0
1 200 aristocrat 0 0 200
2 250 baconian 0 0 250
Bonus 0
Final score 450
