### ISSUE TITLE
Unable to publish a test or schedule a test

### ISSUE THREAD

**Issue by rpochana** [toebes/ciphers#220]
I am not able to publish a test or view already published/ scheduled tests. I had this issue after I deleted one on the published tests this morning. After that for a brief period around 6am , I was able to schedule again. Now again I am not able to schedule or publish tests. I thought it might be an issue with the current account due to data corruption, but have the same issue with the new account. I did try to re-publish the same test though.

**Comment by toebes** [comment]
This was a problem with server overload which we addressed with a major rewrite.
