### ISSUE TITLE
Unable to schedule a test

### ISSUE THREAD

**Issue by MaMaNina** [toebes/ciphers#222]
I am able to publish a test, but not schedule it. After clicking on "schedule test" button, I click "add one" button and wait. Then the folloring error message occurs. "Could not autocreate: Error: The client did not respond in time with model data, while initializing a new model." I did not click anything else, just waited. I click "add one" again, then get this error message "Could not autocreate: ConvergenceError: A request timeout occurred."

**Comment by toebes** [comment]
This was a problem with a server overload which we have addressed by a major restructuring.  It shouldn't happen anymore
