### ISSUE TITLE
Errors in trying to schedule an interactive test

### ISSUE THREAD

**Issue by Gates-Codebusters** [toebes/ciphers#223]
I know you have been working on the overall database, which may be causing related issues, but I was trying to schedule an interactive test, and got error messages that it could not be completed.

![error codes](https://user-images.githubusercontent.com/75402632/104946803-b27ea280-5988-11eb-8d8e-197d40402e87.png)

**Comment by toebes** [comment]
Sorry for the slow response.  This should have been fixed a couple of weeks ago and I forgot to close the issue with the push.  If you do encounter it again, please reopen this issue.

**Comment by Gates-Codebusters** [comment]
Hi John -

I am trying to schedule an interactive test, and keep getting the following
error:
Unable to save test model: TypeError: Cannot read property 'id' of undefined

Not sure if this is the same issue or not, but will try and report as a bug
as well.

Thanks
Jeff Gates
