### ISSUE TITLE
Trouble signing in with google

### ISSUE THREAD

**Issue by azboy1910** [toebes/ciphers#224]
When I am trying to sign in with google, nothing happens to the page, and it just stays there. It doesn't redirect me back to the Toebes website. I am clicking "sign in with Google" and putting in my login information but nothing happens, like I said before it stays on the page shown here.

![image](https://user-images.githubusercontent.com/79338718/108565808-5387b280-72d3-11eb-8e8c-05a73b91a6d1.png)

**Comment by McDonaldSean** [comment]
Hi! Thanks for reporting this issue. 

What is the browser you are using and are you in a private/incognito window?

**Comment by toebes** [comment]
It would also be useful to paste the entire URL when you are in that mode (it should be something like https://toebes.com/codebusters/login.html?returnURL=xxxxx)

**Comment by azboy1910** [comment]
Hi, I am using Firefox and I am not on incognito mode. For some reason, I tried this with another google account and this time it worked.

**Comment by toebes** [comment]
If the account doesn't return a name, we should provide something synthetic to allow the system to continue.
