### ISSUE TITLE
Affine, Morbit, and Pollux Grading

### ISSUE THREAD

**Issue by cyyan88** [toebes/ciphers#225]
![image](https://user-images.githubusercontent.com/52414676/108895115-2db72200-75e1-11eb-9322-6b40e0c87796.png)
![image](https://user-images.githubusercontent.com/52414676/108895161-3c9dd480-75e1-11eb-9017-f34f6f0f2488.png)
![image](https://user-images.githubusercontent.com/52414676/108895187-46bfd300-75e1-11eb-8a8f-200829d0f86a.png)

### Answers were put in yellow boxes during the test (letters entered from the left, no spaces). This is what it shows on the Test Playback end. No points were awarded for these questions.

![image](https://user-images.githubusercontent.com/52414676/108895334-71119080-75e1-11eb-8dd7-d7446c9b28e1.png)
![image](https://user-images.githubusercontent.com/52414676/108895352-766edb00-75e1-11eb-9e4e-3eb478f69744.png)
![image](https://user-images.githubusercontent.com/52414676/108895382-7f5fac80-75e1-11eb-8c34-f60cf2d42b0f.png)

**Comment by RanTheLab** [comment]
The morse code ciphers **require** that the decoded letter be put in the yellow boxes underneath the morse characters for that letter.  You **can not** run the letters all together in the yellow boxes, each letter must be under the corresponding morse code.  

**Note:  Only the yellow boxes are scored!**  Question 14 above does not have anything in the yellow boxes, which are the only thing looked at for scoring.

The screen shot of question 8 above has what might be correct text in the gray box, but only 2 letters are in the yellow boxes and it looks like only the 'X' is correct, thus 26 incorrect letters.
