### ISSUE TITLE
Trouble with Baconian grading + general question

### ISSUE THREAD

**Issue by lgupta2** [toebes/ciphers#226]
Hello!

This is from question 5 on the "North Carolina Regional Test 1".

![image](https://user-images.githubusercontent.com/79619793/109101162-377d7a00-76f4-11eb-831a-1dce0cff6c2a.png)

![image](https://user-images.githubusercontent.com/79619793/109101227-5714a280-76f4-11eb-9f58-1403c113a7c0.png)

I'm not sure where the 36 characters incorrect is coming from, since I got the quote correct. I don't think that it's because I didn't fill out the A/B for each of them, because there are at least 60+ instances of that in the last few rows alone.

For a general question - do our final answers need to be typed into the text boxes (gray with green outline above), or is it fine to leave them in the yellow boxes?

Thank you for all of your work in creating this tool for us!

**Comment by RanTheLab** [comment]
The portion of your answer looks correct, but does not show the complete answer with the 70-ish characters.  Can you provide the testID for this test?  Its the big, long hex number you can find it in the address bar of the test page.  `...html?testID=<big long hex number>`  (or circled in green in the image below)
![image](https://user-images.githubusercontent.com/7691169/109105720-7f080400-76fc-11eb-8915-055bfe43acc2.png)

Your answer **MUST** be in the yellow boxes to be scored.  Think of the gray box as scratch paper that you and your teammates can each see what the other has typed.  

Again, **answers must be entered into the yellow boxes to be scored.**

**Comment by lgupta2** [comment]
I see! The testID is f786158e-dbcf-4c9c-b638-b63ae71a8a8d on the Test Results page and 36fa0e6e-ba62-47cb-b96a-c33074b0e899 on the Test Playback.

**Comment by RanTheLab** [comment]
Unfortunately, our database cleanup routine must have removed the entries for the test.  If you have a recreate, please post it here.
