### ISSUE TITLE
Affine Cipher Doesn't Save

### ISSUE THREAD

**Issue by cyyan88** [toebes/ciphers#228]
Here is my input for the affine cipher **during the test**:
![image](https://user-images.githubusercontent.com/52414676/109735662-223f9a00-7b91-11eb-9bd5-043b4e7b9e13.png)
Here is the **score** for the affine cipher:
![image](https://user-images.githubusercontent.com/52414676/109735689-29ff3e80-7b91-11eb-8a0c-8f859ff1226b.png)
Here is the affine cipher in the **test playback**:
![image](https://user-images.githubusercontent.com/52414676/109735711-31bee300-7b91-11eb-90f7-f36a670f5fdc.png)

**Comment by toebes** [comment]
Could you please provide a little more context on the situation so we can try to diagnose the situation.  What browser/operating system were you using?  What test id was it that was run?  Were there any messages or network disconnects during that time?

**Comment by cyyan88** [comment]
I use Chrome + Windows 10. My partner has the same issue and she also uses Chrome + Mac. This test was generated using the [Codebuilder bot](https://github.com/AC01010/codebuilder). 

I also get this issue when 3 people are taking one test. We usually use the Codebuilder bot, but I don't think it's an issue with the bot since I had this issue while taking the NC Division C Invitational on the site as well (both when doing it individually and as a group). 

I'm not sure what the test id is, but I get an error message (Convergence API could not open model 5ee96dc7-b561-4b41-a0d7-84bdfd4cc65a Error:Error: A model with id '5ee96dc7-b561-4b41-a0d7-84bdfd4cc65a' does not exist.) when I try to edit it in Test Management < Published.

I uploaded the JSON file I imported the test from to Google Drive (https://drive.google.com/file/d/1zvraYgKpBq8IV3YCf1MROhQcfyJioEAs/view?usp=sharing).

I didn't notice any messages/network disconnects during this test, or while we were taking the NC Invitational or other Codebuilder tests.

Thanks!!! Please let me know if you need any more information.

**Comment by toebes** [comment]
Thanks for the repro case!  We were able to find the problem (basically it is related to there being more spaces when the cipher is chunked in groups of 3 and the system didn't allocate enough answer slots

**Comment by toebes** [comment]
We found another issue in which the characters weren't being copied
