### ISSUE TITLE
Errors in scheduling interactive test

### ISSUE THREAD

**Issue by Gates-Codebusters** [toebes/ciphers#229]
I am trying to schedule an interactive test, and get the following errors. Is this something you can help resolve?

Many thanks

![image](https://user-images.githubusercontent.com/75402632/109857925-32a35380-7c29-11eb-9542-029245e0f2d8.png)
![image](https://user-images.githubusercontent.com/75402632/109858025-5070b880-7c29-11eb-8686-a666d1d1995e.png)

**Comment by toebes** [comment]
This has been fixed.  The problem was that the login token had expired and the code didn't show the proper error message indicating that you needed to log in with google/microsoft again.
