### ISSUE TITLE
Can't Publish the Test

### ISSUE THREAD

**Issue by SirAkko** [toebes/ciphers#283]
I try to publish the test but I get an error that says " Unable to save test model: TypeError: Failed to fetch"

If there is a way to fix this that would be great, thank you! 
![EOREOROOROR](https://user-images.githubusercontent.com/91639928/135361194-80b886fe-acc2-40ff-acd7-9842eb1207f7.PNG)

**Comment by toebes** [comment]
Hi we are aware of the issue.  The certificate for the server expired and we are in the process of getting the new one installed.

**Comment by SirAkko** [comment]
> Hi we are aware of the issue. The certificate for the server expired and we are in the process of getting the new one installed.

Thank you!

**Comment by toebes** [comment]
The certificate has been updated and the server is back and running.  Thank you for your patience!
