### ISSUE TITLE
Email addresses not saved when importing tests

### ISSUE THREAD

**Issue by jb836935** [toebes/ciphers#284]
Are there guidelines on how to setup student/class list which can be imported each time a new test needs to be scheduled? I tried exporting test results CSV and importing the same CSV, but it doesn't import email IDs of test takers. Or, can you share CSV format, so that a manually created CSV can be imported with student & test info? It's much easier to edit & maintain the info on local editor and uploading the same.

**Comment by toebes** [comment]
The test deliberately doesn't have the students in it, but you can use a separate file to schedule the test and then import the schedule when running a test.  The schedule file should nominally look like this:

| Time | Length | Timed | User 1 | User 2 | User 3 | School | Type
| --- | --- | --- | --- | --- | --- | --- | --- |
| 10/15/2021 11:45 | 50 | 10 | student1@gmail.com | student2@gmail.com | student3@gmail.com | My School | V |
