### ISSUE TITLE
Porta and Railfence ciphers need to be supported for Division B only for State/National level

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#287]
The current rules don't allow Porta/Railfence at the Regional/Invitational level

**Comment by Kroiririoroirkk** [comment]
I created a Div B State/National test, and I was unable to create either a Porta or Railfence question even though Porta and Railfence cryptanalysis are allowed by the rules. I am attaching a picture demonstrating the issue:

![20211203_161829](https://user-images.githubusercontent.com/20689616/144674813-3aa0a1ef-b934-44f8-a61a-e840ecaf783d.jpg)

Is this intended behavior?
