### ISSUE TITLE
Add the Porta table to the test resource sheet if Porta is used

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#288]

**Comment by toebes** [comment]
The porta table will appear on both the interactive test and the printed test if a porta question is included with the test

**Comment by toebes** [comment]
It doesn't always seem to be showing up

**Comment by MaMaNina** [comment]
The porta table was in the notes, but it was incomplete and incorrect. Just FYI.

**Comment by toebes** [comment]
It should be correct now.  If you find an example where it isn't please attach a screenshot so we can debug.
