### ISSUE TITLE
XSS vulnerability in Test Import

### ISSUE THREAD

**Issue by SuperStormer** [toebes/ciphers#290]
#282 is not fixed by a152d840b073832e2422db8dd07c143a604887b4. There are still many ways to bypass this filter, ie. every payload on [this list](https://portswigger.net/web-security/cross-site-scripting/cheat-sheet).

Sample JSON file:
`
{"TEST.0":{"timed":6222,"count":0,"questions":[],"title":"XSS Demonstration","useCustomHeader":false,"customHeader":"","testtype":"cregional"},"CIPHER.6222":{"cipherString":"This is just a sample question.","cipherType":"aristocrat","encodeType":"random","offset":1,"offset2":1,"keyword":"","keyword2":"","alphabetSource":"ABCDEFGHIJKLMNOPQRSTUVWXYZ","alphabetDest":"BMALZJFQVKTYCRNWUEPDXHIOGS","curlang":"en","replacement":{"A":"B","B":"M","C":"A","D":"L","E":"Z","F":"J","G":"F","H":"Q","I":"V","J":"K","K":"T","L":"Y","M":"C","N":"R","O":"N","P":"W","Q":"U","R":"E","S":"P","T":"D","U":"X","V":"H","W":"I","X":"O","Y":"G","Z":"S"},"operation":"decode","points":123,"question":"<img src/onerror=alert(1)>","editEntry":"6222"}}
`

The correct solution would be to change any user-provided input to be displayed using jQuery .text() instead of .html(), which causes them to be parsed as plaintext and not as HTML.

**Comment by toebes** [comment]
We can't do that for the question text but I will catch other cases.   The main question text has to be formatted for display to the users and must contain html code.   I will continue to look for other ways to close the holes, but calling .text() eliminates a necessary feature of the tests.

**Comment by toebes** [comment]
Remember that when a test is saved and reloaded, we don't know that they edited the JSON file,

**Comment by SuperStormer** [comment]
also occurs on https://toebes.com/aca/ACAProblems.html#

**Comment by toebes** [comment]
It makes sense to go to a whitelist approach
 ```
<strong></strong>
 <i></i>
 <span style="[^"]*"></span>
 <p></p>
 <ul></ul>
 <ol></ol>
 <li></li>
<blockquote></blockquote>
```

or a pattern... 
`</?[a-z]+\s*(style=[^"]*"|)\s*> `

**Comment by toebes** [comment]
> also occurs on https://toebes.com/aca/ACAProblems.html#

That's the same code base. When I push out the fix it will cover it too.

**Comment by SuperStormer** [comment]
I'm a little confused by what you proposed, can I see a code implementation for your proposed fix?

**Comment by toebes** [comment]
Here you go.  Right now this capture group allows a style on the other elements.  I'm tweaking the expression to only allow it on the span.

```
// After we pull in the question we need to filter out 
let re = /<(\/?strong|\/?i|\/?p|\/?ul|\/?ol|\/?li|\/?blockquote|\/?span|)[^>]*(\s+style="[^"]*"|)[^>]*>/gi;
toAdd.question = toAdd.question.replace(re, '<$1$2>');
toAdd.question = toAdd.question.replace(/<>/g, '');
```

You can play with it at https://regex101.com/

**Comment by toebes** [comment]
Here is some more complete code that should catch all the situations.  Let me know if you see any holes left.
```
                    // After we pull in the string, we need to filter it down to only the HTML that we allow.
                    // This is basically a whitelist that only allows a few HTML elements
                    //    strong
                    //    i
                    //    p
                    //    ul
                    //    ol
                    //    li
                    //    blockquote
                    //    span style="xxxx"
                    // Anything else between <> is thrown away, even extra elements on the span
                    //
                    //  To do this we have a complex regexp that whitelists
                    //     <                             Anything that starts with a left bracket            
                    //       (\/?)                       $1 capture group for any leading / (like </ul>)
                    //       (                           $2 capture group for the white list of elements we allow
                    //         strong|
                    //         i|
                    //         p|
                    //         ul|
                    //         ol|
                    //         li|
                    //         blockquote|
                    //         span|
                    //                                   and anything else is ignored
                    //       )  
                    //       (?:                         Third capture group which is ignored.                             
                    //         [^>]*                     Throw away anything that is before the style=
                    //           (                       $3 capture group which gets the style=
                    //             \s+style="[^"]*")|       With double quotes
                    //             \s+style='[^']*')|       or single quotes
                    //                                      or no style at all
                    //           )
                    //       [^>]*
                    //     >
                    const re1 = /<(\/?)(strong|i|p|ul|ol|li|blockquote|span|)(?:[^>]*(\s+style="[^"]*")|)[^>]*>/gi;
                    const re2 = /<(\/?)(strong|i|p|ul|ol|li|blockquote)[^>]*>/gi;
                    // Toss out any malformed HTML elements that don't have their closing >
                    toAdd.question = toAdd.question.replace(/<[^>]*$/, '');
                    // As well as any HTML comments  <!--- and --->
                    toAdd.question = toAdd.question.replace(/<!---.*--->/g, '');
                    // Eliminate all the html elements that we don't like as well as any attribute except style
                    toAdd.question = toAdd.question.replace(re1, '<$1$2$3>');
                    // Get rid of the styles on everything except for the <span elements
                    toAdd.question = toAdd.question.replace(re2, '<$1>');
                    // Get rid of any solo styles (it would come from something like <h1 style="xxx">)
                    toAdd.question = toAdd.question.replace(/<style[^>]*>/gi, '');
                    // Get rid of any empty elements finally
                    toAdd.question = toAdd.question.replace(/<\/?>/g, '');

```

**Comment by SuperStormer** [comment]
HTML comment regex should be `/<!--[^]*-->/g`, though I don't think this affects anything.

Overall, it looks fine to me.

**Comment by toebes** [comment]
Thanks! I appreciate the extra eye.  Keep them coming!
