### ISSUE TITLE
Pollux

### ISSUE THREAD

**Issue by hbkumar** [toebes/ciphers#297]
Pollux cipher question tool does not pick up all the number values put in o - and x bars. It only picks up the first number in each bar and creates the enciphered text.

**Comment by toebes** [comment]
Could you give us an example please?  I just tested a Pollux with a plain text of "test" and 
 O: 123  -:456  X:7890

It generated a result of 
```
591912295
–×●×●●●×–
T E S   T

```
hitting Randomize generated a different one
```
472012384
–×●×●●●×–
T E S   T
```
Hitting Randomize a second time gives
```
691023204
–×●×●●●×–
T E S   T

```
As you can see in this case, I can see ● associated with 1,2, and 3  – with 4,5 and 6 and × with 7,8,9, and 0.

**Comment by hbkumar** [comment]
Hello John,

I’m not facing this issue any more. Thank you and all the very best for the
upcoming SO season!

Sincerely,
Kumar

**Comment by toebes** [comment]
Great. Glad that everything is working.  I will close the issue.  Don't hesitate to report anything else you find.

**Comment by hbkumar** [comment]
Hey John,

I am not sure if you are the right person to direct this query to or I’m
troubling you unnecessarily, but I wanted to understand if there is a
specific point assignment per cipher for the *NC Division B Regional test*.
For example, if the test is 2000 points, then Aristo & Patristo questions -
850 points, Caeser questions - 350, Pollux &Morbit - 425 etc. etc. Or, if
the number of questions per cipher is also a factor.

As Hill and Railfence Ciphers have been removed this year for Division B, I
wanted to understand the make-up of the test.

Any guidance would be appreciated.

Thanks,
Kumar

**Comment by toebes** [comment]
Let me see about posting a good Division B regional sample test with this year's rules.  One thing to pay attention to this year is the special bonus question to encourage teams to do more than just the Aristocrats.

**Comment by toebes** [comment]
You can also send questions to codebusters@toebes.com

**Comment by hbkumar** [comment]
Many thanks!

**Comment by hbkumar** [comment]
Noted with thanks.
