### ISSUE TITLE
Unable to log in at all

### ISSUE THREAD

**Issue by airwreckatron** [toebes/ciphers#320]
I've tried to log in both with google and microsoft, and neither are working. Nothing happens after you enter your credentials (you are not taken to the site, you stay on the 'log in with' page). I have tried both in Incognito and not in Chrome and Firefox with multiple different accounts.

![image](https://user-images.githubusercontent.com/101661082/158432088-88e2af6d-3343-4a10-a9d3-6d8e06870bf0.png)

After signing in, manually going directly to page still says you're not logged in as well.

**Comment by toebes** [comment]
We rebooted the server and it should work now!  Please let us know if it doesn't work for you.

**Comment by toebes** [comment]
We are no longer doing the interactive server this season.
