### ISSUE TITLE
Unable to add codes in test generator

### ISSUE THREAD

**Issue by SraBlouch** [toebes/ciphers#325]
When I log in, I am able to see the usual screen, however upon clicking edit, I am unable to get to the correct screen. If I go to print the test with the current existing questions, I am able to see these questions by scrolling down beyond this new screen that I have not seen before. Unwilling to publicly post images that may contain any of my codes with our upcoming state competition.

**Comment by RanTheLab** [comment]
When you click the print button, you get a screen that shows what the printed test will look like.  On this screen, try printing from the browser to a PDF file and see if that is what you'd expect.
Alternatively, most screen capture tools have the ability to blur out sensitive information.  You could try that and post the blurred images here.

**Comment by toebes** [comment]
If you send a copy of the test to codebusters@toebes.com we can keep it in confidence and determine what is wrong

**Comment by SraBlouch** [comment]
The issue isn't the printing... the issue is that I can't actually edit the test. It is incomplete and I am trying to add new questions. Here is what I am seeing. 

https://www.loom.com/share/769942f388ee4c9a8d679c8f4eabf726

**Comment by RanTheLab** [comment]
OK, it looks like you are using Chrome browser, so you can open the browser console by pressing CRTL+SHIFT+I (letter i), then find the console tab.  Click that edit button like you are doing and capture the output in the console window for us.  You can email any sensitive info to "codebusters <a-with-circle character> toebes.com".  My guess is there is something in your data that it is unhappy about.

**Comment by SraBlouch** [comment]
Thank you! Email just sent from kblouch@cvschools.org
