### ISSUE TITLE
Fix the scoring table for the timed question

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#344]
In the printed page it needs to update the calculations to be 2 points per second instead of 3

**Comment by RanTheLab** [comment]
@toebes 
I picked an easy one for some quick satisfaction...but...the 2022 rules say: 
`A Timing Bonus can be earned based on the number of seconds it takes a team to correctly decode the first question. The timing bonus is equal to 4 x (600 - number of seconds). For example, 6 minutes = 4 x (600-360) = 960 points`
which is 4 points per second... so will 2023 be going from `4 -> 3` or from `4 -> 2`?

**Comment by toebes** [comment]
My bad... Yes, we went from 4 -> 2.  Directly from the new rules:

A Timing Bonus can be earned based on the number of seconds it takes a team to correctly decode the
first question. The timing bonus is equal to 2 x (600 - number of seconds). For example, 6 minutes = 2
x (600-360) = 480 points.
