### ISSUE TITLE
Imported coaches institute Timed question answer key is incorrect

### ISSUE THREAD

**Issue by RanTheLab** [toebes/ciphers#36]
I selected "answer key" after importing the coaches institute sample JSON.  There is an error in the replacement table...for example, 'Z' in the encoded message should be 'S' (there are 7), but the table show `Z -> W` (frequency 7), `S -> Z` (frequency 1), `P -> S` (frequence 0).

Probably a mixup in encoded/cleartext lookup when building that table.  Unless the input wrong (garbage in; garbage out).

Maybe state somewhere that the top row are the letters in the encoded message.

**Comment by RanTheLab** [comment]
I think the frequency counts are incorrectly calculated.

**Comment by toebes** [comment]
Great catch!  Actually I think that the mapping is showing the reverse mapping instead of the direct mapping.  When I compared the counter to the Cipher Counter values at http://toebes.com/Ciphers/CipherCounter.html it seems to match up.
