### ISSUE TITLE
Cryptarithm

### ISSUE THREAD

**Issue by kstaff12** [toebes/ciphers#364]
I have been using the suggested websites to make Cryptarithm formulas which works great. When I come up with a word/phrase for them to decode for the solution on a test, some of my letters are remaining as letters instead of numbers. Is this how it will be in the competition--some letters and some numbers where the kids are converting the numbers to letters? For example, the solution to one of mine was "iced coffee" and it came out as "741D 489911." The D didn't convert to a number. Sometimes, I have several letters that stay letters.

**Comment by toebes** [comment]
If you could send the example to codebusters@toebes.com we can look at what is happening.  In the example you gave, this would be because the letter D isn't used in the actual cryptarithm problem, but it might also be a bug that we missed.

**Comment by toebes** [comment]
We've confirmed that the example was being generated correctly as the letter D was not used in the Cryptarithm.  Let us know if you encounter any other issues!
