### ISSUE TITLE
Fractionated Morse and punctuation

### ISSUE THREAD

**Issue by jlwether** [toebes/ciphers#365]
I'm not sure exactly how the code is written, but I believe the Pollux and Morbit cipher generators can be described as behaving as follows:

1. Convert the plain text to upper case.
2. Replace every character that is not in [A-Z0-9] with a space.
3. Replace every string of spaces with a single space
4. Remove leading and trailing spaces.
5. Convert to Morse code (optionally adding an x at the end to fill out the last pair in Morbit)

I would have expected Fractionated Morse to behave the same way, but it seems to deals with both digits and punctuation differently. My best guess is that it currently does the following:

1. Convert the plain text to upper case.
2.  Remove every character that is not in [ \n\t\rA-Z].
6. Replace every string of white-space characters with a single space.
7. Remove leading spaces -- the trailing spaces are ambiguous in my testing.
8. Convert to Morse code (optionally adding an x or two at the end to fill out the last triple)

The fact that digits silently disappear from Fractionated Morse can lead to problems for the unwary problem setter used to the Pollux and Morbit behavior, but since these are just dropped, it doesn't much affect the kids taking the test. Worse is the fact that words with embedded punctuation such as "I'M" and "DON'T" are treated differently: In the Pollux and Morbit generators these become two words each: "I M" and DON T", but in Fractionated Morse they become one word: "IM" and "DONT". 

Just to make life even more confusing, the display showing how the problem was encoded uses a Morse Code string generated according to the Pollux and Morbit rules, so the displayed Morse Code **does not** agree with the ciphertext. In other words, if you look at the Morse Code displayed by the tool you will think that "I'M" became "I M", but if you decode the ciphertext you get "IM". This discrepancy is more than a bit confusing. 

I think it would be best if the Pollux, Morbit, and FractionatedMorse problem generators all converted the Plain Text into Morse Code in the exact same way.

**Comment by RanTheLab** [comment]
Thanks for the detailed description.  Looking into it.
