### ISSUE TITLE
Fractionated Morse automated solver could be stronger

### ISSUE THREAD

**Issue by jlwether** [toebes/ciphers#367]
The Fractionated Morse automated solver currently recognizes that it can fill in an interval of letters in the alphabetical portion of the keyed alphabet if that interval doesn't contain any letters in the keyword. If an interval does contain letters in the keyword, it won't deduce that that interval can be filled in, **even if it could because all keyword letters in that interval are already known**.  Here are two examples:

<h3>Example 1</h3>
<code>Plain Text: Crimes, like virtues, are their own rewards.
Crib Text: CRIMES
Key: LAW
Keyed alphabet letters that are in the crib: .. W .. E .. IJ .. N ..</code>

The automated solver recognizes that there are 3 letters between E and I and therefore none of the letters FGH can be in the crib, so they must be in the alphabetical portion.  New status:
<code>Known keyed alphabet letters: .. W .. EFGHIJ .. N ..</code>

At this point, the automated solver stops. However, I want to point out that all the letters after N that are in the keyword (namely "W") are already exposed, so it is possible to deduce (and important for students to learn) that this means that the 11 other letters after N **must** go in the 11 slots after N. Then the new status should be:
<code>Known keyed alphabet letters: .. W .. EFGHIJ .. NOPQRSTUVXYZ</code>

At this point we have to stop with the purely formal deductions based on counting. We don't know where the portion before E starts, so we don't know how many letters from that portion are in the keyword. For the portion J .. N, we know that there are 3 possible letters and two slots, so one of KLM must be in the keyword, but we don't know which one.

<h3>Example 2</h3>
Here is another example. Suppose we use the keyword WALL instead of LAW.  

<code>Plain Text: Crimes, like virtues, are their own rewards.
Crib Text: CRIMES
Key: WALL
Keyed alphabet letters that are in the crib: .. L .. E .. IJ .. N ..</code>

In this case, the automated solver again recognized that it can fill in the three letter FGH in the E .. I interval, but it does not recognize that it can also fill in KM in the J .. N interval, even though we already know that L is in the keyword.

I claim that learning to recognize when all keyword letters in an interval have been identified is fairly simple logic for both the automated solver and also for the students who are hoping to learn from it.

Oh, and one more thing: The automated solver seems to want to assume that the last letter in the alphabet is Z; for example, it does this in Example 2, even though there is no way to deduce that from the available known letters.  Yes, it is likely to be true based on letter frequencies, but it should then be stated as a trial assumption, not a deducible fact.

**Comment by RanTheLab** [comment]
I am in the midst of reworking the solver.  Thanks for your examples.
