### ISSUE TITLE
UX -- super nit-picky

### ISSUE THREAD

**Issue by RanTheLab** [toebes/ciphers#39]
### Looking at the atbash/caesar encoder page...

- title is `atbash/caesar`, but buttons are in order `caesar`; `atbash`...
- input text box label (`Text to encode`) should change based on whether `encode` or `decode` button is selected.
- 

### General

- Put `Codebusters Test Tools` before `Other Assistants` in the menu bar.  Codebusters is the main focus of the page.
- Need a legend or readme describing the button behavior (i.e. blue background is selected)
- Need a legend or readme describing the solution (i.e. yellow high-lighted is the solution).
- Label the replacement table with what are letters in coded message vs. letters in decoded message.
- Suggest using "sentence case" throughout.  See [Wikipedia style guide](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Capital_letters)

**Comment by toebes** [comment]
Not at all nitpicky :-) 
  For the atbash/caesar, I think the easiest thing is to just get rid of the second file and only have one version (i.e not both a caesar/atbash and atbash/caesar.  
Good point on the text to encode, but it probably shouldn't be a decode button as the person generating the test puts in the unencoded text.  I'm thinking that it might be more logical for the label to be "Plain Text" unless you can suggest another term.
