### ISSUE TITLE
Unable to print the Test Packet

### ISSUE THREAD

**Issue by deepakannan** [toebes/ciphers#397]
On the Test Packet page, the "Print" button does nothing.

**Comment by toebes** [comment]
We have tried to reproduce this, but need additional information.

What browser/operating system are you using?
Are there any messages or does the screen look funny in any way when you attempt to print?

**Comment by toebes** [comment]
@deepakannan Hi,  We would love to address this issue, but need the information to be able to track it down.  If this is no longer an issue to you please let us know.  If we don't hear anything back we will assume it isn't a problem any more.

**Comment by deepakannan** [comment]
Hi John,
I was sure I responded to this but I guess I didn't. Sorry. After the last
email from you, I tried print to PDF and it worked fine. May have been
either a browser update issue or a glitch that worked itself out.

Sorry again but you may resolve this issue as I cannot reproduce it either.

Thanks for your help.
Deepa

**Comment by toebes** [comment]
Not a problem!  As you can tell, we really try to make sure that things are working from our side.  Thank you for letting us know!
