### ISSUE TITLE
Nihilist Cipher Glitch

### ISSUE THREAD

**Issue by Alecs-Li** [toebes/ciphers#400]
I'm writing a test and the nihilist cipher ruins the format of the PDF print. Also, for some reason I can't print more than 12 questions anymore, my whole interface is glitched. The top of the page looks like the image attached.

![image](https://github.com/toebes/ciphers/assets/76791863/4fda4d3b-b2cf-4dda-ae84-07dc79c75244)

**Comment by Agilus** [comment]
I just encountered this screen also - my test does have a Nihilist cipher in it. Unfortunately, once this bug appeared, I am no longer able to edit my test to remove the Nihilist cipher (or try to fix whatever issue there is) - I am taken to the page shown in the screenshot above when I go to my Test Manager and click Edit Test. The problem also persists if I try to make a duplicate test and edit that one.

**Comment by Agilus** [comment]
Update: This problem resolved for me after the update you pushed out the other day fixing the Cryptarithms. Nihilist ciphers are functional for me again. Not sure whether the OP's problem is also resolved or not.
