### ISSUE TITLE
Cryptarithm defaults to a predictable chart

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#403]
When I use Generate Problems to make a cryptarithm and select one, it gets put into the test and then the chart/workspace is generated in order from 0-9, making it trivial to solve.  What fixes this in the meantime is if I click Check Problem and Update, which changes the letters in the table to the order in which they appear in the problem. However, it is not readily apparent that Check Problem and Update is a clickable button, because it is grayed out (but still functional) at the time when I click on it.

**Comment by toebes** [comment]
Wow, that is a great bug to find.   I will try to push a fix for it later on tonight.

**Comment by toebes** [comment]
It should be fixed.  We now generate the table in alphabetical order always.
