### ISSUE TITLE
Decrypting Ciphertext Encoded in Complete Columnar Transposition Cipher

### ISSUE THREAD

**Issue by seannamorgan** [toebes/ciphers#408]
Hello.  I am trying to generate questions for my team to practice decrypting a code which was encrypted using the complete columnar transposition cipher.  The test is not generating the option to create questions that decrypt codes (only encryption is an option right now, which is not helpful for Division B).  Would you please fix the test generator so decryption questions are able to be created as well?

**Comment by RanTheLab** [comment]
If you could attach screenshots, that would be helpful o clarify the issue. 
Note, the 2024 rules call for decrypting cipher text to plain text ONLY.  This is what the website provides.  As a test writer, you enter plain text, choose the number of columns used to encode, column order used in encoding and a 'crib' which is some part of the plain text.  The Web site shows the solution, but the test packet just shows the encrypted text for students to decode.

**Comment by toebes** [comment]
Hi @seannamorgan,  If you could provide us with a screen snapshot so we can address any issues, it would be greatly appreciated.

**Comment by toebes** [comment]
hi @seannamorgan We would like to resolve this case.  If it is no longer occurring, please let us know.  If we don't hear anything in the next week we will close the case (which can be reopened if the issue crops up again)

**Comment by toebes** [comment]
Hi we haven't gotten a reproducible case. If you do manage to generate one, please reopen this issue with the test case.  Thank you!
