### ISSUE TITLE
Baconian Words punctuation after last word

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#411]
Hi, I learned in reviewing the NC samples (thank you!) that you can add punctuation to Baconian Words problems. (AN ANT A BABY ATTIC etc.) I have experienced that if you make the very last word have a punctuation mark after it, the punctuation mark does not appear in the test packet.

**Comment by toebes** [comment]
Thanks for the nudge.  It was a pretty simple fix.

**Comment by toebes** [comment]
It has been deployed to production
