### ISSUE TITLE
Recommended scores issues

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#457]
Very grateful for the new functionality that suggests points!

I have noticed that if I put in a sentence as a Random Aristocrat, it generates a suggested range of points. If I click K2, it tells me the points should be reduced by 75 and suggests an appropriate score. If I click K1, the text tells me that the points should be **reduced** by 100, but instead the score it suggests is **higher**. 

Also, I would offer that the Fractionated Morse scores might be uniformly low. Obviously choice of keyword, where the crib is, how much the crib helps fill in the remaining text, etc, are significant factors in determining the difficulty of this kind of cipher, so I think the suggested range should be pretty large, but I think in general our experience is that they are often difficult and time-consuming enough to be about on par with a medium aristocrat. The suggester generally offers points in the medium 100s, whereas the NC state and regional test samples generally put them around 250, and there are often times when I think even higher scores are appropriate if we use the aristocrat guidance as a benchmark. A good example is the first (Toni Morrison) cipher in the 2023 Sample Fractionated Morse samples - if we review the work that the autosolver did (or try the cipher ourselves), even the assigned 200 points seems very low for how many times it followed the wrong path when you compare it to the ~250 scores for the Baconian ciphers in the NC State/Regional samples where the A/B pattern was relatively straightforward and easily determined. I leave the final decision to the experts, of course, but just wanted to offer it for review because mid-100s (the suggester put this one around 116) seems quite low. I think my students would skip them at this value which is obviously a strategy, but it would be a shame because it's one of their favorite cipher types.

**Comment by toebes** [comment]
@Agilus Thanks for the feedback!  One thing to note is that the score recommended has some randomness associated to it (it picks a score out of the range given).  Could you confirm that the ranges are indeed higher for your example with a K1 vs K2?  Also note that if you click on the recommend score multiple times, you will get different recommendations.

We will look at the Fractionated Morse scores to see what tweaks can be made.  Having more examples and eyes is definitely useful so we can get this recommendation better.

**Comment by Agilus** [comment]
Yes, the ranges are also higher. It was a significant difference. I've checked two ciphers in response to your comment. Random: 228-239 and 243-249; K1 306-317 and 336-342; K2 153-164 and 168-174, respectively. It seems closest to having added 100 points for being a K1 instead of removing 100 points.

While I am here, it also adds 100 points if you change it to require finding a keyword in a K1, K2, or K3. Finding a K3 keyword is significantly more difficult than finding a K1 or K2 keyword, and I would be happy if the recommendation was in alignment with that.

Thank you for your consideration!

**Comment by toebes** [comment]
If you don't mind sharing screen shots / the plain text you are using, it would be greatly helpful.  Just email it to codebusters@toebes.com so that the quotes don't get shown to the whole world.

**Comment by toebes** [comment]
@Agilus Thanks for the sample phrase! We found and fixed the problem with the Aristocrat.  It occurred when the recommended score for a K1 was < 250 or a K2 < 225.  The code for setting the lower limit had the adjustment backwards.  We have also adjusted the scores for K3 with a different delta when the K3 is part of a keyword solution.

**Comment by Agilus** [comment]
I feel like we want to look at the Patristocrat suggested points. In my recent practice test, I used the test builder to create the following question: 
A quote by Steve Maraboli has been encoded using the K1 Patristocrat Cipher for you to decode. You are told that FADGJ corresponds with the plaintext BEACH. 
Plaintext: Happiness is a state of mind, a choice, a way of living; it is not something to be achieved, it is something to be experienced.
Keyword: SPIDERMAN 
The chi-square value is 22 for this cipher. 

The Suggest Points button dialog says: "Based on analysis of the cipher which includes examining the cipher text for the Chi-Square (χ2) distribution of letters, grade level of the text, number of unknown words, commonality of words, and commonness of pattern words. Encoding as a Patristocrat adds 250 points. A K1 alphabet takes away 100 points, try a score of 378 out of a suggested range of 370 to 379.

NOTE: If you provide any hints in the question, you will want to adjust the score down by approximately 20 points per letter hinted"

This is pretty disparate from the examples in the Guidance.html: 

Regarding hint digits, the Guidance.html says: "With a hint, each letter beyond 3 letters for an Aristocrat (or 5 letters for a Patristocrat) revealed by the hint should drop 50 points from the score."

The Guidance.html also provides a sample cipher with a chi-square value of 11.5, and for that cipher it suggests the following calculation:
"[w]ith a Chi-Square of 11.50, we see multiple short words (it, is, in), and a hint of three letters (man) this problem would be one of the easiest with a score of 200. It would also make for a good timed question. By changing it to a Patristocrat, we would add 500 to get a base score of 700. If we encode it with a K1 alphabet we drop 100 points for a score of 600. At this range we should also be providing a hint that it starts as “isthe” revealing only 5 characters leaving this as a 600 point question."

In 3(e)(iii)(5) it also suggests that a "Patristocrat with a hint should be worth between 450 and 650 points." 

My sense is that 378 is almost always too low for a Patristocrat. But either way, it would be good to work on bringing the Suggested Points and the Guidance.html closer in alignment.

**Comment by toebes** [comment]
I think that they should be more in line now.  I found a flaw in the Patristocrat code which was arbitrarily dropping 75 points in the score and also tweaked the base score adjustment so that is should be more in line now

**Comment by Agilus** [comment]
They are more in line, thanks. I think the only thing they vary on now is the guidance about the hint digits. The Guidance.html suggests only subtracting points for >5 hint digits for a Patristocrat, whereas the pop-up in the tool suggests subtracting 20 for each hint digit given.
