### ISSUE TITLE
Suggestion: Complete Columnar default behavior

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#458]
The default behavior for the Complete Columnar encoder is to add no ordering to the columns, so they are trivial to put back together once the matrix size is determined. It would help test writers who are inexperienced with the tool if it generated a random ordering for these as a default behavior, or popped an error message advising them to select a column ordering other than "none".

**Comment by Agilus** [comment]
Sorry, I see you already have an error message to that effect. I'm helping another coach with a test who had left them all as default and thought it might be because the tool didn't prompt them otherwise. You can close this one out unless you find value in changing the default behavior or making the error message clearer for those unfamiliar with the ciphers.

**Comment by toebes** [comment]
We've added a link next to the message to hopefully make it clearer.  Let us know if this doesn't do the trick!
