### ISSUE TITLE
Add support for recommending keywords to the Fractionated Morse cipher

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#466]

**Comment by Agilus** [comment]
These are very long and increase the difficulty quite a bit, as difficulty increases greatly when the crib draws widely from the alphabet. While the gold "harder" ones are on the right, if they have enough repeating characters, they will actually make the FracMo easier to solve. 

In my experience this morning, they are sufficiently long and drawing widely enough from the alphabet (e.g. FORECASTING) that it is difficult for me to choose a crib that will give students somewhere to start in solving these. 

I'd be tempted to offer a variety of lengths, as you do for some other cipher types. Maybe in the 6-8 range?
