### ISSUE TITLE
Typographical fixes in Suggested Questions

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#468]
If I make a Nihilist and fill in the Quote Author field and put a quote, then the Suggested Question contains two instances of the word "by", as follows: 
The following quote by by Elizabeth Gilbert needs to be decoded with the Nihilist Substitution Cipher with a keyword of LOVE and polybius key of AUTHENTICITY.

If I make an aristocrat with a K1-K4 keyword (whether it is a Decode or a Keyword/Keyphrase question) and use the Suggested Question, it is lacking a space in the question between "the" and "KX", as follows:
A quote by Robert Downey, Jr. has been encoded using theK1 Aristocrat Cipher for you to decode.

**Comment by toebes** [comment]
Fixed!  Thanks for finding them
