### ISSUE TITLE
Suggestion: Recovering K3 keyword/phrase support

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#469]
I would love to see Guidance specific to creating ciphers that are good candidates for recovering a K3 keyword. Specifically, a cipher is a better candidate for recovering a K3 keyword if almost all of the alphabet is used in the plaintext. The less of the alphabet that is used, the more difficult the problem becomes, but letter frequencies in the plaintext still need to be distributed enough to make it solvable (i.e., if many letters are only used once, this creates its own difficulty factor for solving the Aristocrat before beginning the recovery process). It is also harder if competitors need to interleave two 13-letter loops than if they are able to recover only one 26-letter loop. Lastly, it becomes even more difficult if the decimation factor is even and therefore results in an alternating interleave spacing. 

I would also be very happy if the tool had a check for whether a cipher is a good candidate for recovering a K3 keyword. A plaintext that contains 23 different letters is a pretty solid contender for solving these, but one that contains only 16 letters of the alphabet is a poor candidate for this type of problem. If as a test writer I can get that information upfront, it will help prevent ESes from inadvertently making these too difficult during competitions. As a test writer, I'd also love to know upfront whether the decimation factor is even or odd without having to solve it by hand to see how it came out. 

Thanks for your consideration on how to better support these.

**Comment by toebes** [comment]
Good suggestion.  

There are currently two things in place to mitigate this

- The testbuilder will only recommend quotes with at least 19 unique characters.  This is backed up by the aristocrat encoder complaining when there are less than 19 unique characters in the quote.  Additionally when generating a K3 keyword, it also looks for a lower χ2 value.
- The new suggest keyword feature for K3 will only recommend an offset of 1,2 or 3 characters.  

Assuming that both of these conditions are met, (>19 unique characters and the offset is 3 or less) then recovering a keyword should be doable.   Personally I almost always use an offset of 1.

However as you pointed out, generating a stronger warning about the difficulty of the K3 recovery is warranted.  Additionally, I've been considering writing an auto-K3 solver as part of the solutions page and using that solver to guide the difficulty.  This is probably a month or so out on the list to do.

By the way, I found two good articles on solving K3 that are worth linking to:
[The Black Chamber: recovering-k-3-alphabets-a-paper-and-pencil-approach/](https://theblackchamber552383191.wordpress.com/2020/11/18/recovering-k-3-alphabets-a-paper-and-pencil-approach/)
[The Black Chamber: finding-k3-alphabets-again-the-nerd-version/](https://theblackchamber552383191.wordpress.com/2020/11/21/finding-k3-alphabets-again-the-nerd-version/)

**Comment by Agilus** [comment]
That sounds fantastic, and I'm excited to see it when it comes out.

I am wondering if, in the meantime, the team is willing to put some Guidance about these in the Guidance.html that is linked to when you click the Guidance button. Currently, if I open the Guidance and look for K3, it doesn't appear at all. I'd be pretty happy if it had its own subsection for ESes to learn how to best ensure that these are solvable (for keyword recovery only). 

Between a draft test I've seen for an upcoming competition and our state starting a new initiative to provide resources for first-time ESes before our upcoming regional competitions, I'm hoping to be able to point people to carefully follow the Guidance on these, FracMos, and Patristocrats, which in my experience are the three in this year's Invitational/Regional rules that can be most at risk of not being solvable in competition time. If I throw together practice tests too quickly without reviewing these cipher types, this is where I've run into problems throughout the season. This way, if someone cares and wants to do a good job, there's a place where they can learn what to be mindful of as they make these, even if the technology piece isn't in place yet. Thank you!

**Comment by toebes** [comment]
We are more than happy to add guidance.... If you care to write up anything to contribute, we would never reject it!

**Comment by Agilus** [comment]
I can take a stab at it and send it over tomorrow :)

**Comment by Agilus** [comment]
Well, hopefully brevity is not in fact the soul of wit.

Feel free to edit and use as is helpful to you, but here's my attempt at some Guidance for K1-3 keyword recovery problems following your existing format.
https://docs.google.com/document/d/1KG6QMk2E1kLNz9GjTaUDFkaCBbgj-Ca0SA6cDsiJX9g/edit?usp=sharing

**Comment by toebes** [comment]
Great Write-up!  
It is deployed to https://toebes.com/codebusters/TestGuidance.html#Aristocrat_Keyword
and in the process, the guidance jumps to that if you are working on a keyword cipher.
