### ISSUE TITLE
Xenocrypt suggested points

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#471]
I just used the Test Builder + Quote Manager to make a practice test for today, and while one of my Xenocrypts came in around a likely appropriate neighborhood for suggested points at a quick glance, this one seems to come in too low:

Todo cambió el día que descubrió que había suficiente tiempo para las cosas importantes de su vida.

The Suggested Points dialogue says "Based on analysis of the cipher which includes examining the cipher text for the Chi-Square (χ2) distribution of letters, grade level of the text, number of unknown words, commonality of words, and commonness of pattern words. A single letter A/I which maps to A/I makes it 25 points easier, try a score of 306 out of a suggested range of 304 to 385."
Chi-Square=16 [Easy] Length=78 [Short] Unique=19

I am not entirely sure what it is considering, as the plaintext does not have any single letter words in it. Though if I click K1 and use the keyword REVELATION the text about the A/I mapping goes away and the points are suggested thusly: A K1 alphabet takes away 100 points, try a score of 231 out of a suggested range of 229 to 310.

The Keyword Generator (which I am new to) also does not generate a Keyword for this one, and I am not sure what makes it unable to do so.

My other Xenocrypt from the Quote Manager:
Lo que te digas a ti mismo, en silencio o en voz alta, le dice a tu cerebro en qué enfocarte. ¡Sencillo!
Chi-Square=71 [Extremely Difficult] Length=77 [Short] Unique=19
ends up with suggested points of 677 as a K1 and the Keyword Generator works on it. 

I'm just not sure there is a 450 point difference in the difficulty of these two ciphers, and would like to see the first one get some type of bonus for being in Spanish so that it is not scored exactly the same as an English language aristocrat, but I brought the second one in as an example because we also may not want to outsize the points on that one. I can see how they go over at practice but thought in any case I'd send these examples over for review.

**Comment by toebes** [comment]
Thanks for pointing it out.  As it turns out the code for detecting the Xenocrypt was incorrect and it didn't give it the score bonus expected. The problem with the single letter was the analysis code which didn't expect the accented characters.
