### ISSUE TITLE
Saving Bug with "Suggest Question"

### ISSUE THREAD

**Issue by Pojoto** [toebes/ciphers#474]
For some ciphers (Hill is one of them), pressing the "Suggest Question" button does not register the program requiring the user to save the question, despite the question text changing. 

If you press "Suggest Question", and leave the page, the question text does not get saved. Additionally, the "Save" button never turns red, indicating it needs to be saved.

**Comment by toebes** [comment]
This is because the replaceQuestionText() routine doesn't call markundo!
