### ISSUE TITLE
background graphics not printing on Morse tables

### ISSUE THREAD

**Issue by jenniferdevlin** [toebes/ciphers#482]
Thank you for the tip "You may have to turn on background graphics when printing if the colors don't show up". Indeed, when I turn on background graphics, the grey highlighting on the Porta table and the alphabets below the table does show up.  However, even with background graphics on, the helpful grey highlighting on the Morse tables does not show up.  A lower priority suggestion is to remove the grey highlighting between the smaller tables (as seen in the top half and lower, left corner of this example) in the Morse code section of the resource sheet (like seen in the lower, right corner of this example).
<img width="1386" alt="Screen Shot 2024-01-28 at 11 54 41 AM" src="https://github.com/toebes/ciphers/assets/125524378/0f421ca8-f1b1-4cd2-9d01-18ceb9327fd8">

**Comment by toebes** [comment]
The table is now properly colored without the stray grey
