### ISSUE TITLE
Nihilist appears partially printed over Polybius table

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#487]
Hi,

I'm taking a draft test for an upcoming competition in which the Nihilist cipher has partially printed over the top of the Polybius table. I'll email the sample case over.

**Comment by toebes** [comment]
Fixed!  Thanks for reporting it

**Comment by Agilus** [comment]
This problem has recurred for me with a Nihilist cryptanalysis:

Question text: The following quote has been encoded with the Nihilist Substitution Cipher using a very common word for the key. The 45th through 49th cipher units (57 67 78 66 75) decode to be SWORD.

Plain text: I love the valiant; but it is not enough to wield a broadsword, one must also know against whom.

PKEY: CREMATION
KEY: SLEAZY
Crib: SWORD
Block size: 0
