### ISSUE TITLE
Caesar will line wrap at an apostrophe

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#488]
Hi,

In the draft test I'm taking, a word has an apostrophe in it, and the Caesar encoder writes everything up through and including the apostrophe on one line, and the rest of the contraction on the next line. 

Because it's not very easy to tell an apostrophe from a comma in the ciphertext, it would be better if it would force an entire contraction to wrap together.

Thanks for your consideration.

**Comment by Agilus** [comment]
Probably relatedly, the aristocrat will line wrap both before and after a double quote ("). 

Sample case: "Just living is not enough," said the butterfly, "one must have sunshine, freedom, and a little flower."

- The double quote right before "one" appears on the first line with the word ONE appearing on the second line
- The end double quote after the period appears alone on its own line.

**Comment by toebes** [comment]
Actually the issue with the apostrophe was not with the normal one `'` but with the right `’` and left `‘`
We have fixed that.   It turns out that doing the same thing with `"` `“` and `”` also seems to fix the sample case.
