### ISSUE TITLE
Nihilist printing bug results in overlapping content

### ISSUE THREAD

**Issue by Pojoto** [toebes/ciphers#490]
To reproduce the case:

Keyword: HUMOR
Polybius key: OPTIMISTIC
Plaintext: Don't worry about the world coming to an end today. It is already tomorrow in Australia.

Then examine the 'Print' version of the question.

**Comment by toebes** [comment]
It should already be fixed.  Check https://github.com/toebes/ciphers/issues/487 to confirm please
