### ISSUE TITLE
Xenocrypt character count, accents

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#491]
I have noticed that the character count for a Xenocrypt does not include characters with accents. This frequently results in the tool claiming that my Xenos are too short for a points recommendation even if they are not.

**Comment by Agilus** [comment]
Thank you - I think in doing so I figured out that I have to click "Spanish" before importing the Spanish quotes, so now all my quotes should be in the right places instead of mixed together as they were before :)

**Comment by toebes** [comment]
Fixed and deployed to production.
