### ISSUE TITLE
FracMo suggested points if no keyword/crib present

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#494]
I'm using the Test Builder to make a practice test. If I create a Fractionated Morse quote with the test builder and then quickly click through the "Suggest Points"/"Suggest Question" buttons, then I notice that if I did not populate the Fractionated Morse tool with a keyword or a crib, the dialogue tells me that it went through -1 iterations and there are -1 cipher characters left to be determined, making a solution fairly easy to reach. The points are in the 220s. You might want it to just pop a dialogue telling users to input a keyword and crib to get a suggested points value instead.

**Comment by RanTheLab** [comment]
Good one!  Thanks!
