### ISSUE TITLE
Fractionated Morse Keyword suggestions.

### ISSUE THREAD

**Issue by RanTheLab** [toebes/ciphers#497]
These are very long and increase the difficulty quite a bit, as difficulty increases greatly when the crib draws widely from the alphabet. While the gold "harder" ones are on the right, if they have enough repeating characters, they will actually make the FracMo easier to solve. 

In my experience this morning, they are sufficiently long and drawing widely enough from the alphabet (e.g. FORECASTING) that it is difficult for me to choose a crib that will give students somewhere to start in solving these. 

I'd be tempted to offer a variety of lengths, as you do for some other cipher types. Maybe in the 6-8 range?

_Originally posted by @Agilus in https://github.com/toebes/ciphers/issues/466#issuecomment-1959731616_

**Comment by toebes** [comment]
The current dialog provides keywords in the 8-11 character range of unique characters in the first two columns and the same for non-unique characters in the last column.

I've updated the code to change it to be

left two columns, first 10 are the 8-11 unique characters that they have been
Next 10 are 6-7 unique characters
Right column, same - 10 of the 8-11 non-unique characters

**Comment by toebes** [comment]
It has been pushed to production.
