### ISSUE TITLE
K2 Patristocrat keyword suggestion

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#498]
There must be something I am not understanding about the K2 Patristocrat Keyword Suggestion. 

Quote: The unrecorded past is none other than our old friend, the tree in the primeval forest which fell without being heard.

When I click on Suggest Keyword, it says "For K2 alphabets, not all of the letters of the keyword will be mapped. Those with a single letter not mapped are shown as yellow buttons instead of blue."

But what I am finding in practice is that if I click on a blue button, 1-2 letters will be unmapped. If I click on a yellow button, 0-1 letters will be unmapped. 

So I think I'm not understanding what the directions are telling me about the difference between yellow and blue. Also, in this case, yellow seems to be the easier ones whereas in other keywords, yellow is reserved for harder ones?

**Comment by toebes** [comment]
@Agilus Can I get an example with the keyword not being mapped?  Remember that for a K2 you have a double lookup so the frequency below the keyword is not that of the keyword.

**Comment by Agilus** [comment]
Yeah, this one was on me. I had to sit down and work one instead of looking at the results in the tool for exactly the reason you describe. Thanks for clearing it up!

**Comment by toebes** [comment]
Ok here you go:
Given this K2 keyword (which came from a yellow button) 
![image](https://github.com/toebes/ciphers/assets/12609253/23762679-fa31-4942-ac68-77f1df94aa83)
It now shows in green which letters are mapped so you can clearly see which letters aren't known
![image](https://github.com/toebes/ciphers/assets/12609253/30af35d2-c053-4736-9e9d-80634c8a1c9d)

**Comment by Agilus** [comment]
Thank you! I know this one was on me, but I think this new functionality you have added will help test writers have a clearer idea of what information the competitors will have access to.

**Comment by toebes** [comment]
Happy to help!
