### ISSUE TITLE
Going to the Xenocrypt from the pull down menu causes a crash when entering accented characters

### ISSUE THREAD

**Issue by toebes** [toebes/ciphers#501]
If you go to the test generation tools pulldown menu and select Xenocrypt, it brings you to:
`https://toebes.com/codebusters/XenocryptEncrypt.html?cipherType=aristocrat`
![image](https://github.com/toebes/ciphers/assets/12609253/e6cecdbc-aba1-4756-ae0d-71fe26360238)

instead of clicking on the xenocrypt button on the main page which brings you to 
`https://toebes.com/codebusters/XenocryptEncrypt.html?cipherType=aristocrat&curlang=es`
![image](https://github.com/toebes/ciphers/assets/12609253/1500c8fc-1ad9-4222-8599-563a1fa8b0a6)

Note the difference of the curlang not being specified in the menu

Once there, change the language from English to Spanish

Then enter a plain text string of:
`abcde üñéáíóúüñéáíóúüñéáíóúüñéáíóúüñéáíóúdx`

and you should see an error.

The problem is that the state.replacement field is not set up to include the `ñ` character.  

When changing the language, that field should be reinitialized to avoid the problem

**Comment by SuperIronDragon** [comment]
Fixed! The issue was that it wasn't regenerating the encoding table when changing the language so it didn't have anything corresponding to ñ.
