### ISSUE TITLE
State/Nationals columnar crib length error

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#502]
If my test type is C - State/Nationals, it still throws an error if the crib for my columnar is shorter than one fewer than the number of columns used. But the State/Nats rules for Columnar C allow a crib no shorter than 3 fewer than the number of columns. 

Finally getting a report submitted for it from a comment in this issue:  _Originally posted by @Agilus in https://github.com/toebes/ciphers/issues/495#issuecomment-1960691527_

**Comment by RanTheLab** [comment]
Thanks for opening this. Pushed into production.
