### ISSUE TITLE
typo in Fractionated Morse Solving Guide table

### ISSUE THREAD

**Issue by jenniferdevlin** [toebes/ciphers#503]
The 10th column in the table shown throughout the example should be dash-dot-dot (rather than dot-dot-dot) . . . "Solving a Sample Fractionated Morse Cipher" Solving Guide (https://toebes.com/codebusters/Samples/Solving_Fractionated_Morse.htm).  Both the 1st and 10th column are shown as dot-dot-dot.

<img width="461" alt="Screen Shot 2024-02-28 at 1 25 16 PM" src="https://github.com/toebes/ciphers/assets/125524378/474334af-e95e-435c-b618-2293019d8ac4">

**Comment by toebes** [comment]
This was previously fixed, I just forgot to close the issue.
