### ISSUE TITLE
Complete Columnar Cryptanalysis Bug

### ISSUE THREAD

**Issue by kstaff12** [toebes/ciphers#508]
The system does not recognize "10" and "11" when I'm providing the column order. It seems to see double digits as single digits.

**Comment by RanTheLab** [comment]
Thanks for pointing this out--this is how it was intended to work, however I added some language to clarify this the in test guidance for Complete Columnar.
![image](https://github.com/toebes/ciphers/assets/7691169/9ad1bd06-b857-4cc7-b161-8b540456566e)
