### ISSUE TITLE
"Answers and Solutions" does not include solutions

### ISSUE THREAD

**Issue by ericop** [toebes/ciphers#509]
Expected:
When I visit (I know my local storage in browser has my question, so you can't follow my links, I just give them for reference of the path I'm on) the &sols=y should cause the solutions to render on the page even before I press The Print button 
https://toebes.com/codebusters/TestAnswers.html?test=0&sols=y

Actual:
https://toebes.com/codebusters/TestAnswers.html?test=0&sols=y and https://toebes.com/codebusters/TestAnswers.html?test=0 show the exact same generated content that excludes the solutions.

When I go to edit my Nihilist Substitution Encoder question on https://toebes.com/codebusters/NihilistSubstitutionEncrypt.html?cipherType=nihilistsub&editEntry=19 if I scroll down I see the following section. I expect it to also print when on the **Answers and Solutions** page

> ## How to solve
> Step 1: Fill out the Polybius Table
> Given the Polybius Key ULTRASONIC, we can fill out the first 10 spaces of the polybius table, with each unique letter taking up a space. (Skip any duplicate letters)
> Note: Treat the letters I and J as one single letter I/J
> ...

**Comment by RanTheLab** [comment]
closed with commit #f5f106b
