### ISSUE TITLE
Columnar Solver unable to solve, reason unknown

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#520]
I decided to challenge my students today by providing MORE information than I needed to, and using fewer columns than I think they would expect me to. The surprising result is that the Complete Columnar solver is unable to solve this one. I really don't know why. Is it because my crib is longer than the number of columns?

Quote: The backbone of surprise is fusing speed with secrecy.
Columns: 4
Ordering: 8308 (Randomly generated)
Crib: FUSING

- It tries 4 columns first and outputs: Crib not found, rule out an encoding of 4 columns. Then it proceeds to try 6 and 8 columns, doesn't find the crib there either for obvious reasons, and then gives up. 
- While writing up this issue, I did try changing the ordering many (>10) times, and the issue persisted regardless of the ordering I used, including if I use the natural order of 1234.

**Comment by toebes** [comment]
If the crib happens to span three rows, have the autosolver only include the first <n> characters of the crib where <n> is the number of columns + 1 in order to avoid the problem.
