### ISSUE TITLE
Nihilist cryptanalysis consider providing keyword length

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#550]
We discussed the possibility of providing the keyword length for Nihilist cryptanalysis problems to make them a bit less time-intensive and more likely to be attempted by competitors. 
- Do we want to change the Suggest Question dialog to support this?
- Do we want to provide the keyword length to the AutoSolver?
- If we move forward with it, I can update the TestGuidance.html to include this new guidance.

**Comment by toebes** [comment]
Need to wait for #425
