### ISSUE TITLE
Complete Columnar character count

### ISSUE THREAD

**Issue by Agilus** [toebes/ciphers#562]
When the complete columnar character counter tells the numbers of characters in the cipher, it includes punctuation. The punctuation should be stripped when determining the cipher text length.

**Comment by RanTheLab** [comment]
Thoughts on this?
![image](https://github.com/user-attachments/assets/70d98c7c-3a26-4948-88a9-691d2d4581ee)

**Comment by Agilus** [comment]
I like this — both the informative warning and the plain text length.
